settings:
  configreloadpermission: 'admin.reload'
  noperm: '&cYou don''t have permission to execute this command!'
  reloaded: '&aYou successfully reloaded the configuration!'
  scoreboard:
    name: 'scoreboard'
    lines:
      0: 'This is a score'
      1: 'thing'
      2: '&acolored score'
      3: '&kkkk &rting &kkkk'